[build]
builder = "nixpacks"

[deploy]
startCommand = "python run_both_bots.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
FORWARD_MODE = "copy"
MESSAGE_DELAY = "1"
LOG_LEVEL = "INFO"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"