services:
  - type: web
    name: telegram-userbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run_both_bots.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: SOURCE_CHAT_ID
        sync: false
      - key: TARGET_CHAT_ID
        sync: false
      - key: FORWARD_MODE
        value: copy
      - key: MESSAGE_DELAY
        value: "1"
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONUNBUFFERED
        value: "1"